### ISSUE TITLE
Hope to migrate to .Net 6

### ISSUE THREAD

**Issue by Reknij** [nilaoda/N_m3u8DL-CLI#583]
Migrating to .Net 6 has no effect on window users, but it is useful for linux users. For example, I now download videos in the window and copy them to my own server (mainly playing the video through jellyfin). If Linux supports it, I can download the video directly on the server.

**Comment by nilaoda** [comment]
Will

**Comment by ac1982** [comment]
```C#
csc /define:DEBUG /optimize /out:N_m3u8DL-CLI.exe *.cs
Microsoft (R) Visual C# Compiler version 4.8.4161.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

Downloader.cs(34,37): error CS1043: { or ; expected
Downloader.cs(35,38): error CS1043: { or ; expected
Downloader.cs(36,37): error CS1043: { or ; expected
Downloader.cs(37,36): error CS1043: { or ; expected
Downloader.cs(38,33): error CS1043: { or ; expected
Downloader.cs(39,32): error CS1043: { or ; expected
Downloader.cs(40,34): error CS1043: { or ; expected
Downloader.cs(41,32): error CS1043: { or ; expected
Downloader.cs(42,34): error CS1043: { or ; expected
Downloader.cs(43,35): error CS1043: { or ; expected
Downloader.cs(44,34): error CS1043: { or ; expected
Downloader.cs(45,44): error CS1043: { or ; expected
Downloader.cs(46,38): error CS1043: { or ; expected
Downloader.cs(47,38): error CS1043: { or ; expected
Downloader.cs(48,37): error CS1043: { or ; expected
Downloader.cs(49,36): error CS1043: { or ; expected
DownloadManager.cs(391,137): error CS1056: Unexpected character '$'
DownloadManager.cs(545,120): error CS1056: Unexpected character '$'
DownloadManager.cs(28,42): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(29,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(30,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(30,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
DownloadManager.cs(30,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
DownloadManager.cs(31,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(31,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
DownloadManager.cs(31,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
DownloadManager.cs(32,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(32,54): error CS1519: Invalid token '.' in class, struct, or interface member declaration
DownloadManager.cs(32,60): error CS1519: Invalid token ';' in class, struct, or interface member declaration
DownloadManager.cs(33,48): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(34,47): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(35,48): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(36,48): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(36,56): error CS1519: Invalid token '.' in class, struct, or interface member declaration
DownloadManager.cs(36,62): error CS1519: Invalid token ';' in class, struct, or interface member declaration
DownloadManager.cs(37,42): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(38,59): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(39,53): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(40,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(41,43): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(42,50): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(43,47): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(44,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(45,64): error CS1519: Invalid token '=' in class, struct, or interface member declaration
DownloadManager.cs(46,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
FFmpeg.cs(28,29): error CS1056: Unexpected character '$'
FFmpeg.cs(38,37): error CS1056: Unexpected character '$'
FFmpeg.cs(38,120): error CS1056: Unexpected character '$'
FFmpeg.cs(53,25): error CS1056: Unexpected character '$'
FFmpeg.cs(57,25): error CS1056: Unexpected character '$'
FFmpeg.cs(57,122): error CS1056: Unexpected character '$'
FFmpeg.cs(16,55): error CS1519: Invalid token '=' in class, struct, or interface member declaration
FFmpeg.cs(16,63): error CS1519: Invalid token '.' in class, struct, or interface member declaration
FFmpeg.cs(16,69): error CS1519: Invalid token ';' in class, struct, or interface member declaration
FFmpeg.cs(17,55): error CS1519: Invalid token '=' in class, struct, or interface member declaration
FFmpeg.cs(17,63): error CS1519: Invalid token '.' in class, struct, or interface member declaration
FFmpeg.cs(17,69): error CS1519: Invalid token ';' in class, struct, or interface member declaration
FFmpeg.cs(18,55): error CS1519: Invalid token '=' in class, struct, or interface member declaration
FFmpeg.cs(19,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Global.cs(37,32): error CS1056: Unexpected character '$'
Global.cs(41,31): error CS1056: Unexpected character '$'
Global.cs(42,31): error CS1056: Unexpected character '$'
Global.cs(58,38): error CS1056: Unexpected character '$'
Global.cs(59,126): error CS1056: Unexpected character '$'
Global.cs(64,132): error CS1056: Unexpected character '$'
Global.cs(65,126): error CS1056: Unexpected character '$'
Global.cs(727,43): error CS1056: Unexpected character '$'
Global.cs(30,45): error CS1043: { or ; expected
Global.cs(31,42): error CS1043: { or ; expected
Global.cs(32,52): error CS1043: { or ; expected
Global.cs(37,32): error CS1525: Invalid expression term ''
Global.cs(37,33): error CS1002: ; expected
Global.cs(1228,10): error CS1513: } expected
Global.cs(1248,13): error CS1519: Invalid token 'for' in class, struct, or interface member declaration
Global.cs(1248,44): error CS1003: Syntax error, '>' expected
Global.cs(1248,44): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Global.cs(1248,47): error CS1519: Invalid token '++' in class, struct, or interface member declaration
Global.cs(1251,17): error CS1519: Invalid token 'if' in class, struct, or interface member declaration
Global.cs(1251,35): error CS1519: Invalid token '(' in class, struct, or interface member declaration
Global.cs(1251,39): error CS1519: Invalid token ',' in class, struct, or interface member declaration
Global.cs(1253,23): error CS1519: Invalid token '>' in class, struct, or interface member declaration
Global.cs(1256,21): error CS1519: Invalid token 'if' in class, struct, or interface member declaration
Global.cs(1256,33): error CS1519: Invalid token '==' in class, struct, or interface member declaration
Global.cs(1260,29): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Global.cs(1260,39): error CS1519: Invalid token '+' in class, struct, or interface member declaration
Global.cs(1260,51): error CS1519: Invalid token '-' in class, struct, or interface member declaration
Global.cs(1260,61): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1261,34): error CS1519: Invalid token '-' in class, struct, or interface member declaration
Global.cs(1261,44): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1262,33): error CS1519: Invalid token '-=' in class, struct, or interface member declaration
Global.cs(1264,30): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Global.cs(1264,39): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Global.cs(1265,38): error CS1002: ; expected
Global.cs(1265,54): error CS1519: Invalid token '(' in class, struct, or interface member declaration
Global.cs(1265,58): error CS1519: Invalid token ',' in class, struct, or interface member declaration
Global.cs(1269,29): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Global.cs(1269,42): error CS1519: Invalid token '(' in class, struct, or interface member declaration
Global.cs(1269,50): error CS1519: Invalid token ',' in class, struct, or interface member declaration
Global.cs(1269,52): error CS1520: Method must have a return type
Global.cs(1269,69): error CS1001: Identifier expected
Global.cs(1269,75): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1269,86): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1269,100): error CS1520: Method must have a return type
Global.cs(1269,117): error CS1001: Identifier expected
Global.cs(1269,121): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1269,132): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Global.cs(1272,17): error CS0116: A namespace cannot directly contain members such as fields or methods
Global.cs(1272,42): error CS1518: Expected class, delegate, enum, interface, or struct
Global.cs(1273,13): error CS1022: Type or namespace definition, or end-of-file expected
HLSLiveDownloader.cs(26,37): error CS1043: { or ; expected
HLSLiveDownloader.cs(27,37): error CS1043: { or ; expected
HLSLiveDownloader.cs(28,44): error CS1043: { or ; expected
HLSLiveDownloader.cs(29,38): error CS1043: { or ; expected
IqJsonParser.cs(38,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(39,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(40,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(44,35): error CS1056: Unexpected character '$'
IqJsonParser.cs(67,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(68,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(69,31): error CS1056: Unexpected character '$'
IqJsonParser.cs(75,35): error CS1056: Unexpected character '$'
IqJsonParser.cs(76,35): error CS1056: Unexpected character '$'
IqJsonParser.cs(105,27): error CS1056: Unexpected character '$'
IqJsonParser.cs(106,21): error CS1056: Unexpected character '$'
IqJsonParser.cs(107,21): error CS1056: Unexpected character '$'
IqJsonParser.cs(108,21): error CS1056: Unexpected character '$'
LOGGER.cs(42,72): error CS1056: Unexpected character '$'
MPDParser.cs(527,49): error CS1056: Unexpected character '$'
MPDParser.cs(528,30): error CS1056: Unexpected character '$'
MPDParser.cs(529,31): error CS1056: Unexpected character '$'
MPDParser.cs(530,48): error CS1056: Unexpected character '$'
MPDParser.cs(531,48): error CS1056: Unexpected character '$'
MPDParser.cs(532,75): error CS1056: Unexpected character '$'
MPDParser.cs(533,34): error CS1056: Unexpected character '$'
MPDParser.cs(534,28): error CS1056: Unexpected character '$'
MPDParser.cs(541,57): error CS1056: Unexpected character '$'
MPDParser.cs(644,27): error CS1056: Unexpected character '$'
MPDParser.cs(645,21): error CS1056: Unexpected character '$'
MPDParser.cs(646,21): error CS1056: Unexpected character '$'
MPDParser.cs(647,21): error CS1056: Unexpected character '$'
MPDParser.cs(666,31): error CS1056: Unexpected character '$'
MPDParser.cs(667,31): error CS1056: Unexpected character '$'
MPDParser.cs(670,27): error CS1056: Unexpected character '$'
MPDParser.cs(671,27): error CS1056: Unexpected character '$'
MPDParser.cs(681,35): error CS1056: Unexpected character '$'
MPDParser.cs(685,35): error CS1056: Unexpected character '$'
MPDParser.cs(728,31): error CS1056: Unexpected character '$'
MPDParser.cs(735,35): error CS1056: Unexpected character '$'
MPDParser.cs(20,74): error CS1513: } expected
MPDParser.cs(77,13): error CS1519: Invalid token 'if' in class, struct, or interface member declaration
MPDParser.cs(77,29): error CS1519: Invalid token '!=' in class, struct, or interface member declaration
MPDParser.cs(79,17): error CS1520: Method must have a return type
MPDParser.cs(79,42): error CS1001: Identifier expected
MPDParser.cs(80,17): error CS1520: Method must have a return type
MPDParser.cs(80,50): error CS1001: Identifier expected
MPDParser.cs(82,33): error CS1519: Invalid token '[' in class, struct, or interface member declaration
MPDParser.cs(82,34): error CS1001: Identifier expected
MPDParser.cs(82,34): error CS1519: Invalid token '"SegmentUrls"' in class, struct, or interface member
        declaration
MPDParser.cs(82,67): error CS1519: Invalid token '(' in class, struct, or interface member declaration
MPDParser.cs(83,45): error CS1002: ; expected
MPDParser.cs(83,60): error CS1519: Invalid token ')' in class, struct, or interface member declaration
MPDParser.cs(85,45): error CS1519: Invalid token '(' in class, struct, or interface member declaration
MPDParser.cs(87,41): error CS1519: Invalid token '[' in class, struct, or interface member declaration
MPDParser.cs(87,42): error CS1001: Identifier expected
MPDParser.cs(87,42): error CS1519: Invalid token '"SegmentUrls"' in class, struct, or interface member
        declaration
MPDParser.cs(87,57): error CS1520: Method must have a return type
MPDParser.cs(87,61): error CS1031: Type expected
MPDParser.cs(87,94): error CS1519: Invalid token '(' in class, struct, or interface member declaration
MPDParser.cs(89,21): error CS0116: A namespace cannot directly contain members such as fields or methods
MPDParser.cs(91,42): error CS1001: Identifier expected
MPDParser.cs(93,17): error CS1022: Type or namespace definition, or end-of-file expected
MPDParser.cs(94,13): error CS1022: Type or namespace definition, or end-of-file expected
MPDParser.cs(95,13): error CS0116: A namespace cannot directly contain members such as fields or methods
MPDParser.cs(104,42): error CS1001: Identifier expected
MPDParser.cs(105,21): error CS1022: Type or namespace definition, or end-of-file expected
MyOptions.cs(20,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration
MyOptions.cs(26,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
MyOptions.cs(59,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
MyOptions.cs(62,44): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(22,24): error CS1056: Unexpected character '$'
Parser.cs(33,24): error CS1056: Unexpected character '$'
Parser.cs(181,64): error CS1056: Unexpected character '$'
Parser.cs(225,28): error CS1056: Unexpected character '$'
Parser.cs(227,28): error CS1056: Unexpected character '$'
Parser.cs(235,28): error CS1056: Unexpected character '$'
Parser.cs(237,28): error CS1056: Unexpected character '$'
Parser.cs(625,61): error CS1056: Unexpected character '$'
Parser.cs(655,61): error CS1056: Unexpected character '$'
Parser.cs(810,43): error CS1056: Unexpected character '$'
Parser.cs(56,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(56,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(56,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(57,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(57,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(57,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(58,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(58,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(58,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(59,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(59,54): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(59,60): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(60,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(60,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(60,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(62,52): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(63,50): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(65,48): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(67,53): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(68,51): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(69,45): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(69,53): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(69,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(70,47): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(70,55): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(70,61): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Parser.cs(71,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(72,43): error CS1519: Invalid token '=' in class, struct, or interface member declaration
Parser.cs(72,51): error CS1519: Invalid token '.' in class, struct, or interface member declaration
Parser.cs(72,57): error CS1519: Invalid token ';' in class, struct, or interface member declaration
Program.cs(149,54): error CS1056: Unexpected character '$'
Program.cs(153,54): error CS1056: Unexpected character '$'
Program.cs(303,34): error CS1056: Unexpected character '$'
Program.cs(304,34): error CS1056: Unexpected character '$'
Program.cs(345,38): error CS1056: Unexpected character '$'
Program.cs(347,27): error CS1056: Unexpected character '$'
Watcher.cs(66,19): error CS1056: Unexpected character '$'
Watcher.cs(86,19): error CS1056: Unexpected character '$'
Watcher.cs(106,19): error CS1056: Unexpected character '$'
Watcher.cs(20,32): error CS1043: { or ; expected
Watcher.cs(21,30): error CS1043: { or ; expected
Watcher.cs(22,37): error CS1043: { or ; expected
Watcher.cs(23,50): error CS1043: { or ; expected
```

**Comment by Reknij** [comment]
https://github.com/Reknij/N_m3u8DL-CLI
I trying migrate to dotnet 6.

**Comment by ac1982** [comment]
> https://github.com/Reknij/N_m3u8DL-CLI I trying migrate to dotnet 6.
Success build your folk, but can not download file.

```bash
Unhandled exception. System.ArgumentException: Invalid resource type 'N_m3u8DL_CLI_core.strings'! strings is not visible for the parser! Change resources 'Access Modifier' to 'Public' (Parameter 'HelpText')
   at CommandLine.Infrastructure.LocalizableAttributeProperty.GetLocalizedValue()
   at CommandLine.Infrastructure.LocalizableAttributeProperty.get_Value()
   at CommandLine.BaseAttribute.get_HelpText()
   at CommandLine.Core.ValueSpecification.FromAttribute(ValueAttribute attribute, Type conversionType, IEnumerable`1 enumValues)
   at CommandLine.Core.Specification.FromProperty(PropertyInfo property)
   at CommandLine.Core.InstanceBuilder.<>c__0`1.<Build>b__0_1(PropertyInfo pi)
   at CommandLine.Core.ReflectionExtensions.<>c__DisplayClass0_0`1.<GetSpecifications>b__5(IGrouping`2 g)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CSharpx.EnumerableExtensions.Memoize[T](IEnumerable`1 source)
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at N_m3u8DL_CLI_core.Program.Main(String[] args) in C:\Downloads\N_m3u8DL-CLI-master\N_m3u8DL-CLI\Program.cs:line 181

```

**Comment by Reknij** [comment]
> > https://github.com/Reknij/N_m3u8DL-CLI I trying migrate to dotnet 6.
> > Success build your folk, but can not download file.
> 
> ```shell
> Unhandled exception. System.ArgumentException: Invalid resource type 'N_m3u8DL_CLI_core.strings'! strings is not visible for the parser! Change resources 'Access Modifier' to 'Public' (Parameter 'HelpText')
>    at CommandLine.Infrastructure.LocalizableAttributeProperty.GetLocalizedValue()
>    at CommandLine.Infrastructure.LocalizableAttributeProperty.get_Value()
>    at CommandLine.BaseAttribute.get_HelpText()
>    at CommandLine.Core.ValueSpecification.FromAttribute(ValueAttribute attribute, Type conversionType, IEnumerable`1 enumValues)
>    at CommandLine.Core.Specification.FromProperty(PropertyInfo property)
>    at CommandLine.Core.InstanceBuilder.<>c__0`1.<Build>b__0_1(PropertyInfo pi)
>    at CommandLine.Core.ReflectionExtensions.<>c__DisplayClass0_0`1.<GetSpecifications>b__5(IGrouping`2 g)
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at CSharpx.EnumerableExtensions.Memoize[T](IEnumerable`1 source)
>    at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors)
>    at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
>    at N_m3u8DL_CLI_core.Program.Main(String[] args) in C:\Downloads\N_m3u8DL-CLI-master\N_m3u8DL-CLI\Program.cs:line 181
> ```

fix already.
